[EDELIVERY-2252] New uploadPmode.sh script, remove pmode upload from Dockerfile, rename get_artefacts.sh to run.sh

diff --git a/Domibus-MSH-docker/src/main/docker/tomcat/Dockerfile b/Domibus-MSH-docker/src/main/docker/tomcat/Dockerfile
--- a/Domibus-MSH-docker/src/main/docker/tomcat/Dockerfile
+++ b/Domibus-MSH-docker/src/main/docker/tomcat/Dockerfile
@@ -16,10 +16,10 @@ ENV SOURCE_CODE ${SOURCE_CODE}
 
 ARG PARTY
 ENV PARTY ${PARTY:-blue}
-ENV PMODE_NAME "domibus-gw-sample-pmode-$PARTY.xml"
+#ENV PMODE_NAME "domibus-gw-sample-pmode-$PARTY.xml"
 
 RUN echo $PARTY
-RUN echo $PMODE_NAME
+#RUN echo $PMODE_NAME
 
 ENV TOMCAT_MAJOR 8
 ENV TOMCAT_VERSION 8.0.24
@@ -62,8 +62,8 @@ RUN sed -i 's/\r$//' $CATALINA_HOME/bin/setenv.sh
 RUN sed -i 's/#export CATALINA_HOME=<YOUR_INSTALLATION_PATH>/sleep 120;/g' $CATALINA_HOME/bin/setenv.sh
 RUN sed -i 's/#JAVA_OPTS/JAVA_OPTS/g' $CATALINA_HOME/bin/setenv.sh
 RUN sed -i 's/4096/1024/g' $CATALINA_HOME/bin/setenv.sh
-RUN sed -i 's/<blue_hostname>:8080/domibusblue:8080/g' $DOMIBUS_DIST/conf/pmodes/$PMODE_NAME
-RUN sed -i 's/<red_hostname>:8080/domibusred:8080/g' $DOMIBUS_DIST/conf/pmodes/$PMODE_NAME
+#RUN sed -i 's/<blue_hostname>:8080/domibusblue:8080/g' $DOMIBUS_DIST/conf/pmodes/$PMODE_NAME
+#RUN sed -i 's/<red_hostname>:8080/domibusred:8080/g' $DOMIBUS_DIST/conf/pmodes/$PMODE_NAME
 RUN sed -i "s/localhost:3306/mysql$PARTY:3306/g" $CATALINA_HOME/conf/domibus/domibus.properties
 RUN sed -i "s/serverName=localhost/serverName=mysql$PARTY/g" $CATALINA_HOME/conf/domibus/domibus.properties
 RUN echo "s/localhost:3306/mysql$PARTY:3306/g"
@@ -77,8 +77,8 @@ RUN cp doNothingPolicy.xml $CATALINA_HOME/conf/domibus/policies/
 RUN echo '#!/bin/bash' >> $DOMIBUS_DIST/entrypoint.sh
 RUN echo "cd $CATALINA_HOME" >> $DOMIBUS_DIST/entrypoint.sh
 RUN echo './bin/catalina.sh start' >> $DOMIBUS_DIST/entrypoint.sh
-RUN echo "while ! curl --output /dev/null --silent --head --fail http://localhost:8080/domibus/home; do sleep 1 && echo -n . ; done" >> $DOMIBUS_DIST/entrypoint.sh
-RUN echo "curl --user $ADMIN_USER:$ADMIN_PASSW -X POST -F pmode=@\"$DOMIBUS_DIST/conf/pmodes/$PMODE_NAME\" http://localhost:8080/domibus/home/uploadPmodeFile" >> $DOMIBUS_DIST/entrypoint.sh
+#RUN echo "while ! curl --output /dev/null --silent --head --fail http://localhost:8080/domibus/; do sleep 1 && echo -n . ; done" >> $DOMIBUS_DIST/entrypoint.sh
+#RUN echo "curl --user $ADMIN_USER:$ADMIN_PASSW -X POST -F pmode=@\"$DOMIBUS_DIST/conf/pmodes/$PMODE_NAME\" http://localhost:8080/domibus/home/uploadPmodeFile" >> $DOMIBUS_DIST/entrypoint.sh
 RUN echo "while true ; do sleep 1 ; done;" >> $DOMIBUS_DIST/entrypoint.sh
 RUN chmod 777 $DOMIBUS_DIST/entrypoint.sh
 EXPOSE 8080
